version: '3.12'

services:
  clients_management_api:
    build: .
    container_name: clients_management_api
    env_file: .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@clients_management_database:${DATABASE_PORT}/${DATABASE_NAME}
    ports:
      - "8080:${BACKEND_PORT}"
    depends_on:
      - clients_management_database

  clients_management_database:
    image: postgres:17
    container_name: clients_management_database
    env_file: .env
    environment:
      - DATABASE_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
