version: '3.12'

services:
  clients_management:
    build: .
    container_name: clients_management
    ports:
      - "8080:8000"
    depends_on:
      - clients_management_database

  clients_management_database:
    image: postgres:17
    container_name: clients_management_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
