services:
  clients_management_api:
    container_name: clients_management_api
    build: .
    env_file: .env
    ports:
      - "8080:8000"
    depends_on:
      - clients_management_database
    networks:
      - clients_management_net

  clients_management_database:
    image: postgres:17
    container_name: clients_management_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - clients_management_net

volumes:
  pgdata:

networks:
  clients_management_net:
    driver: bridge
