version: '3.12'

services:
  clients_management_api:
    build: .
    container_name: clients_management_api_container
    env_file: .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@database:${DATABASE_PORT}/${DATABASE_NAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - clients_management_database

  clients_management_database:
    image: postgres:17
    container_name: clients_management_database_container
    env_file: .env
    environment:
      - DATABASE_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
