"""added claimed_at in violations

Revision ID: 021ce6cbe28b
Revises: 42fbbb60f289
Create Date: 2025-06-02 15:27:12.317867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021ce6cbe28b'
down_revision: Union[str, None] = '42fbbb60f289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violation', 'claimed_at')
    # ### end Alembic commands ###
