"""one to many client season_ticket

Revision ID: 14568a5647c3
Revises: cd482dc88f2c
Create Date: 2025-06-02 16:30:35.508559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14568a5647c3'
down_revision: Union[str, None] = 'cd482dc88f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_season_ticket_id_fk', 'client', type_='foreignkey')
    op.drop_column('client', 'season_ticket_id')
    op.add_column('season_ticket', sa.Column('client_id', sa.Uuid(), nullable=False))
    op.create_foreign_key('season_ticket_id_fk', 'season_ticket', 'client', ['client_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('season_ticket_id_fk', 'season_ticket', type_='foreignkey')
    op.drop_column('season_ticket', 'client_id')
    op.add_column('client', sa.Column('season_ticket_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('client_season_ticket_id_fk', 'client', 'season_ticket', ['season_ticket_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
