"""violations added

Revision ID: 75ea8866c1a1
Revises: e24dec685686
Create Date: 2025-06-02 14:08:05.991700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ea8866c1a1'
down_revision: Union[str, None] = 'e24dec685686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('detail', sa.String(length=256), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='violation_id_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='violation_pkey'),
    comment='Таблица с записями о нарушениях клиентов.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation')
    # ### end Alembic commands ###
