"""renamed name to type in group

Revision ID: cd482dc88f2c
Revises: 021ce6cbe28b
Create Date: 2025-06-02 16:15:11.387153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd482dc88f2c'
down_revision: Union[str, None] = '021ce6cbe28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('type', sa.String(length=256), nullable=False))
    op.drop_column('group', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('group', 'type')
    # ### end Alembic commands ###
