"""season tickets added

Revision ID: df0c7a898d3c
Revises: 4c1b2e6cc8e3
Create Date: 2025-05-23 20:30:55.889353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0c7a898d3c'
down_revision: Union[str, None] = '4c1b2e6cc8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_ticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='season_ticket_pkey'),
    comment='Таблица с записями об абонементах клиентов.'
    )
    op.add_column('client', sa.Column('season_ticket_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'season_ticket_id')
    op.drop_table('season_ticket')
    # ### end Alembic commands ###
