"""foring keys problem solved

Revision ID: e24dec685686
Revises: 43c885569885
Create Date: 2025-05-23 20:45:04.698396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24dec685686'
down_revision: Union[str, None] = '43c885569885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('client_season_ticket_id_fk', 'client', 'season_ticket', ['season_ticket_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_season_ticket_id_fk', 'client', type_='foreignkey')
    # ### end Alembic commands ###
