"""Инициализация БД

Revision ID: fea6f2d00985
Revises: 
Create Date: 2025-05-19 19:09:41.114874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea6f2d00985'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=False),
    sa.Column('patronymic', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('photo_url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name='client_pkey'),
    comment='Таблица с записями о клиентах.'
    )
    op.create_table('group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name='group_pkey'),
    comment='Таблица с записями о группах клиентов.'
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('refresh_token', sa.String(length=256), nullable=True, comment='Токен обновления токена доступа.'),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_uk'),
    sa.UniqueConstraint('username', name='user_username_uk'),
    comment='Таблица с записями о пользователях.'
    )
    op.create_table('comment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='comment_client_id_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='comment_user_id_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='comment_pkey'),
    comment='Таблица с записями о комментариях пользователей о клиентах.'
    )
    op.create_table('relationship',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='relationship_client_id_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='relationship_group_id_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='relationship_pkey'),
    comment='Таблица с записями о связях между клиентами.'
    )
    op.create_table('visit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('visit_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='visit_client_id_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='visit_pkey'),
    comment='Таблица с записями о посещениях.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_table('relationship')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('client')
    # ### end Alembic commands ###
