name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Set up .env file
        run: |
          touch .env
          echo '${{ secrets.ENV_FILE }}' > .env
          cat .env
          
      - name: Check if the directory exists
        run: ls -alh

      - name: Print current directory
        run: pwd

      - name: Copy project to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            mkdir -p ~/sport_monitor/backend/clients_management
          EOF
  
          rsync -az --delete ./backend/clients_management/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/sport_monitor/backend/clients_management

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ~/sport_monitor/backend/clients_management
            set -a
            source .env
            set +a
            cat .env
            docker compose down
            docker compose up -d --build
          EOF
