name: Test and Deploy

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  test-clients-management-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/clients_management

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load Poetry cache
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            backend/clients_management/.venv
          key: poetry-${{ hashFiles('backend/clients_management/poetry.lock') }}

      - name: Install dependencies with Poetry
        run: poetry install --no-interaction --no-root

      - name: Set up .env file
        run: |
          touch .env
          echo '${{ secrets.ENV_FILE }}' > .env

      - name: Run tests
        run: poetry run pytest tests

  deploy:
    needs: test-clients-management-api
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Set up .env files
        run: |
          touch ./backend/clients_management/.env
          echo '${{ secrets.CLIENTS_MANAGEMENT_ENV_FILE }}' > ./backend/clients_management/.env
          
          touch ./backend/clients_management/docker.env
          echo '${{ secrets.CLIENTS_MANAGEMENT_DOCKER_ENV_FILE }}' > ./backend/clients_management/docker.env

      - name: Copy project to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ~/sport_monitor"
  
          rsync -az --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/sport_monitor

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ~/sport_monitor/backend/clients_management
          
            docker compose --env-file docker.env down --remove-orphans
            docker compose --env-file docker.env build --pull
            docker compose --env-file docker.env up -d --wait
          EOF
